import productImg from "../../img/product.png";
export const armrestData = {
  opel: [
    {
      name: "Opel Astra G",
      price: 60,
      pic: productImg,
      brand: "Astra G",
      info: "",
    },
    {
      name: "Opel Zafira",
      price: 60,
      pic: productImg,
      brand: "Zafira",
      info: "",
    },
    {
      name: "Opel Astra H",
      price: 60,
      pic: productImg,
      brand: "Astra H",
      info: "",
    },
  ],
  lada: [
    {
      name: "Vaz2121 Niva4x4",
      price: 60,
      pic: productImg,
      brand: "Lada",
      info: "",
    },
    {
      name: "Vaz2107(01)",
      price: 60,
      pic: productImg,
      brand: "Lada",
      info: "",
    },
    {
      name: "Lada Priora",
      price: 60,
      pic: productImg,
      brand: "Priora",
      info: "",
    },
    {
      name: "Vaz21010(012)",
      price: 60,
      pic: productImg,
      brand: "Lada",
      info: "",
    },
    {
      name: "Vaz21099",
      price: 60,
      pic: productImg,
      brand: "Lada",
      info: "",
    },
    {
      name: "Lada Granta",
      price: 60,
      pic: productImg,
      brand: "Granta",
      info: "",
    },
  ],
  volkswagen: [
    {
      name: "Volkswagen Golf3, Golf4, Vento, Bora",
      price: 60,
      pic: productImg,
      brand: "Golf",
      info: "",
    },
  ],
  mitsubishi: [
    {
      name: "Mitsubishi Pajero IO",
      price: 60,
      pic: productImg,
      brand: "Pajero",
      info: "",
    },
  ],
  nissan: [
    {
      name: "Nissan March",
      price: 60,
      pic: productImg,
      brand: "March",
      info: "",
    },
    {
      name: "Nissan Juke",
      price: 60,
      pic: productImg,
      brand: "Juke",
      info: "",
    },
    {
      name: "Nissan X-Trail",
      price: 60,
      pic: productImg,
      brand: "X-Trail",
      info: "",
    },
    {
      name: "Nissan Tiida",
      price: 60,
      pic: productImg,
      brand: "Tiida",
      info: "",
    },
    {
      name: "Nissan Versa",
      price: 60,
      pic: productImg,
      brand: "Versa",
      info: "",
    },
  ],
  chevrolet: [
    {
      name: "Chevrolet Niva",
      price: 60,
      pic: productImg,
      brand: "Niva",
      info: "",
    },
  ],
  ford: [
    {
      name: "Ford Transit",
      price: 60,
      pic: productImg,
      brand: "Transit",
      info: "",
    },
  ],
  bmw: [
    {
      name: "BMW E46",
      price: 60,
      pic: productImg,
      brand: "E46",
      info: "",
    },
  ],
  toyota: [
    {
      name: "Toyota Vitz",
      price: 60,
      pic: productImg,
      brand: "Vitz",
      info: "",
    },
  ],
  suzuki: [
    {
      name: "Suzuki SX4",
      price: 60,
      pic: productImg,
      brand: "SX4",
      info: "",
    },
  ],
  mercedes: [
    {
      name: "Mercedes W202(C-180)",
      price: 60,
      pic: productImg,
      brand: "Mercedes",
      info: "",
    },
  ],
  renault: [
    {
      name: "Renault Duster",
      price: 60,
      pic: productImg,
      brand: "Duster",
      info: "",
    },
  ],
  kia: [
    {
      name: "Kia Rio 2017+",
      price: 60,
      pic: productImg,
      brand: "Rio",
      info: "",
    },
  ],
  honda: [
    {
      name: "Honda Fit",
      price: 60,
      pic: productImg,
      brand: "Fit",
      info: "",
    },
  ],
};

export const oldArmrestData = [
  {
    name: "Opel Astra G",
    price: 60,
    pic: productImg,
    type: "Opel",
  },
  {
    name: "Vaz2121 Niva4x4",
    price: 60,
    pic: productImg,
    type: "Lada",
  },
  {
    name: "Opel Zafira",
    price: 60,
    pic: productImg,
    type: "Opel",
  },
  {
    name: "Volkswagen Golf3, Golf4, Vento, Bora",
    price: 60,
    pic: productImg,
    type: "Volkswagen",
  },
  {
    name: "Mitsubishi Pajero IO",
    price: 60,
    pic: productImg,
    type: "Mitsubishi",
  },
  {
    name: "Nissan March",
    price: 60,
    pic: productImg,
    type: "Nissan",
  },
  {
    name: "Vaz2107(01)",
    price: 60,
    pic: productImg,
    type: "Lada",
  },
  {
    name: "Chevrolet Niva",
    price: 60,
    pic: productImg,
    type: "Chevrolet",
  },
  {
    name: "Lada Priora",
    price: 60,
    pic: productImg,
    type: "Lada",
  },
  {
    name: "Vaz21010(012)",
    price: 60,
    pic: productImg,
    type: "Lada",
  },
  {
    name: "Ford Transit",
    price: 60,
    pic: productImg,
    type: "Ford",
  },
  {
    name: "Vaz21099",
    price: 60,
    pic: productImg,
    type: "Lada",
  },
  {
    name: "Vaz21015(013,014)",
    price: 60,
    pic: productImg,
    type: "Lada",
  },
  {
    name: "BMW E46",
    price: 60,
    pic: productImg,
    type: "BMW",
  },
  {
    name: "Nissan Juke",
    price: 60,
    pic: productImg,
    type: "Nissan",
  },
  {
    name: "Nissan X-Trail",
    price: 60,
    pic: productImg,
    type: "Nissan",
  },
  {
    name: "Opel Astra H",
    price: 60,
    pic: productImg,
    type: "Opel",
  },
  {
    name: "Toyota Vitz",
    price: 60,
    pic: productImg,
    type: "Toyota",
  },
  {
    name: "Nissan Tiida",
    price: 60,
    pic: productImg,
    type: "Nissan",
  },
  {
    name: "Suzuki SX4",
    price: 60,
    pic: productImg,
    type: "Suzuki",
  },
  {
    name: "Mercedes W202(C-180)",
    price: 60,
    pic: productImg,
    type: "Mercedes",
  },
  {
    name: "Renault Duster",
    price: 60,
    pic: productImg,
    type: "Renault",
  },
  {
    name: "Kia Rio 2017+",
    price: 60,
    pic: productImg,
    type: "Kia",
  },
  {
    name: "Nissan Versa",
    price: 60,
    pic: productImg,
    type: "Nissan",
  },
  {
    name: "Honda Fit",
    price: 60,
    pic: productImg,
    type: "Honda",
  },
  {
    name: "Lada Granta",
    price: 60,
    pic: productImg,
    type: "Lada",
  },
];
